server:
  port: 8080
  servlet:
    context-path: /api/

spring:
  application:
    name: Tech-Manager
  output:
    ansi:
      enabled: ALWAYS

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    doc-expansion: none
    writer-with-order-by-keys: true
    operationsSorter: method
